/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControlNewFrame;
import static controlador.ControlNewFrame.seleccionarConversion;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.Conversor;
import static modelo.Conversor.ocurrencia1;
import modelo.TipodeConversion;

/**
 *
 * @author jhan_
 */
public class InterfazConversor extends javax.swing.JFrame {
    
    /**
     * Creates new form InterfazConversor
     */
    public InterfazConversor() {
        initComponents();
        opciondeConversion.addItem(TipodeConversion.MONEDA.getTipodeConversion());
        opciondeConversion.addItem(TipodeConversion.TEMPERATURA.getTipodeConversion());
        
       
       
    }

//    public JComboBox<String> getOpciondeConversion() {
//        return opciondeConversion;
//    }
//
//    public JComboBox<String> getTipodeCambio() {
//        return tipodeCambio1;
//    }
//
//    public JComboBox<String> getTipodeCambio2() {
//        return tipodeCambio1;
//    }

    public JTextField getValor() {
        return valor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        opciondeConversion = new javax.swing.JComboBox<>();
        valor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tipodeCambio1 = new javax.swing.JComboBox<>();
        tipodeCambio2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(75, 146, 196));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("De");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 70, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccionar conversor ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 210, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("A");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 60, -1));

        opciondeConversion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opciondeConversionItemStateChanged(evt);
            }
        });
        opciondeConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opciondeConversionActionPerformed(evt);
            }
        });
        jPanel1.add(opciondeConversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 230, 32));
        jPanel1.add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 230, 28));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Convertir");
        jButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jButton1ItemStateChanged(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 230, 33));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor a convertir");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 170, -1));

        tipodeCambio1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipodeCambio1ItemStateChanged(evt);
            }
        });
        jPanel1.add(tipodeCambio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 230, 30));

        tipodeCambio2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipodeCambio2ItemStateChanged(evt);
            }
        });
        jPanel1.add(tipodeCambio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 182, 230, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/low-poly-grid-haikei.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jButton1ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ItemStateChanged

    private void opciondeConversionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opciondeConversionItemStateChanged
        // TODO add your handling code here:
      seleccionarConversion(tipodeCambio1, tipodeCambio2, opciondeConversion);
        
    }//GEN-LAST:event_opciondeConversionItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Conversor.valor =  valor.getText();
        
     if(!valor.getText().isEmpty()){
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea Continuar?");
        
        if(respuesta ==0){
        
        try {
            // TODO add your handling code here:

            Conversor.convertirDivisa();
        } catch (IOException ex) {
            Logger.getLogger(InterfazConversor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        }
        
            }else{
     
     
                 JOptionPane.showMessageDialog(null, "Campo vacio");
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void opciondeConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opciondeConversionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opciondeConversionActionPerformed

    private void tipodeCambio1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipodeCambio1ItemStateChanged
        // TODO add your handling code here:
        
     if(tipodeCambio1.getItemCount() != 0){
      String ocurrencia1 =     tipodeCambio1.getSelectedItem().toString();
      Conversor.ocurrencia1 = ocurrencia1.substring(ocurrencia1.length()-4, ocurrencia1.length()-1);
      System.out.println(ocurrencia1);
     }
                         
             
               
       
          
        
    }//GEN-LAST:event_tipodeCambio1ItemStateChanged

    private void tipodeCambio2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipodeCambio2ItemStateChanged
        // TODO add your handling code here:
        
           if(tipodeCambio2.getItemCount() != 0){
            String ocurrencia2 =     tipodeCambio2.getSelectedItem().toString();
            Conversor.ocurrencia2 = ocurrencia2.substring(ocurrencia2.length()-4, ocurrencia2.length()-1);
               System.out.println(ocurrencia2);
           }
           
           
//            
//              // ;
//               
//        System.out.println(ocurrencia2);
            
    
       
        
    }//GEN-LAST:event_tipodeCambio2ItemStateChanged

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> opciondeConversion;
    private javax.swing.JComboBox<String> tipodeCambio1;
    private javax.swing.JComboBox<String> tipodeCambio2;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
