/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControlNewFrame;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import modelo.TipodeConversion;

/**
 *
 * @author jhan_
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form otro
     */
    public Interfaz() {
        initComponents();
        opciondeConversion.addItem(TipodeConversion.MONEDA.getTipodeConversion());
        opciondeConversion.addItem(TipodeConversion.TEMPERATURA.getTipodeConversion());
       
    }

    public JComboBox<String> getOpciondeConversion() {
        return opciondeConversion;
    }

    public JComboBox<String> getTipoDeCambio() {
        return tipoDeCambio;
    }

    public JComboBox<String> getTipoDeCambio2() {
        return tipoDeCambio2;
    }

    public JTextField getValor() {
        return valor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tipoDeCambio2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        opciondeConversion = new javax.swing.JComboBox<>();
        tipoDeCambio = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        tipoDeCambio2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tipoDeCambio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoDeCambio2ActionPerformed(evt);
            }
        });
        jPanel1.add(tipoDeCambio2);
        tipoDeCambio2.setBounds(190, 190, 120, 30);

        jLabel1.setText("Seleccionar Conversor");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 30, 130, 20);

        opciondeConversion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        opciondeConversion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opciondeConversionItemStateChanged(evt);
            }
        });
        jPanel1.add(opciondeConversion);
        opciondeConversion.setBounds(190, 50, 120, 30);

        tipoDeCambio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tipoDeCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoDeCambioActionPerformed(evt);
            }
        });
        jPanel1.add(tipoDeCambio);
        tipoDeCambio.setBounds(190, 130, 120, 30);

        jLabel3.setText("A");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 170, 130, 20);

        jLabel4.setText("Valor a convertir");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 240, 130, 20);

        jLabel5.setText("De");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 110, 130, 20);
        jPanel1.add(valor);
        valor.setBounds(190, 260, 120, 30);

        jLabel6.setText("A");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(190, 170, 130, 20);

        jButton1.setText("Convertir");
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 320, 100, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 1.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 450, 370);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 440, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoDeCambio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDeCambio2ActionPerformed

           // TODO add your handling code here:
    }//GEN-LAST:event_tipoDeCambio2ActionPerformed

    private void tipoDeCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDeCambioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoDeCambioActionPerformed

    private void opciondeConversionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opciondeConversionItemStateChanged
        // TODO add your handling code here:
          ControlNewFrame.seleccionarConversion(tipoDeCambio,tipoDeCambio2,opciondeConversion);
    }//GEN-LAST:event_opciondeConversionItemStateChanged

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> opciondeConversion;
    private javax.swing.JComboBox<String> tipoDeCambio;
    private javax.swing.JComboBox<String> tipoDeCambio2;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
